name: Build and Push Docker image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ykim25 }}
          password: ${{ secrets.dckr_pat_uPjPFxIm24Hcw8KUBYOshbSii_I}}
    
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: foosball/
          push: true
          tags: ykim25umbc/docker-github-action:${{ github.run_number }}

